# Generated by Django 2.0 on 2018-04-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('user_name', models.CharField(max_length=100, verbose_name='用户名称')),
                ('user_head', models.ImageField(upload_to='./head/', verbose_name='用户头像')),
            ],
        ),
    ]
