# Generated by Django 2.0 on 2018-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_news_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='new_context',
            field=models.CharField(max_length=200, verbose_name='回答者主键'),
        ),
    ]
