# Generated by Django 2.0 on 2018-04-07 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180407_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_img',
            old_name='school_ph',
            new_name='school_pic',
        ),
    ]
