# Generated by Django 2.0 on 2018-04-07 07:34

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180407_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='school_add',
        ),
        migrations.AddField(
            model_name='college',
            name='college_url',
            field=models.URLField(null=True, verbose_name='学院网址'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_abst',
            field=models.TextField(null=True, verbose_name='学校简介'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_address',
            field=models.CharField(max_length=200, null=True, verbose_name='学校地址'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_belong',
            field=models.CharField(max_length=50, null=True, verbose_name='学校隶属'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_feat',
            field=models.CharField(max_length=100, null=True, verbose_name='院校特色'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_location',
            field=models.CharField(max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_mold',
            field=models.CharField(max_length=100, null=True, verbose_name='学校类型'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_tel',
            field=models.CharField(max_length=50, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_url',
            field=models.URLField(null=True, verbose_name='学校网址'),
        ),
        migrations.AlterField(
            model_name='fare_line',
            name='fare_arts',
            field=models.CharField(max_length=20, null=True, verbose_name='文科'),
        ),
        migrations.AlterField(
            model_name='fare_line',
            name='fare_batch',
            field=models.CharField(max_length=50, null=True, verbose_name='批次'),
        ),
        migrations.AlterField(
            model_name='fare_line',
            name='fare_science',
            field=models.CharField(max_length=20, null=True, verbose_name='理科'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='average_score',
            field=models.CharField(max_length=50, null=True, verbose_name='平均分'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='batch',
            field=models.CharField(max_length=100, null=True, verbose_name='批次'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='control_line',
            field=models.CharField(max_length=50, null=True, verbose_name='控制线'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='dics',
            field=models.CharField(max_length=100, null=True, verbose_name='科类'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='enrolment',
            field=models.CharField(max_length=50, null=True, verbose_name='录取人数'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='highest_score',
            field=models.CharField(max_length=50, null=True, verbose_name='最高分'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='major',
            field=models.CharField(max_length=200, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='over_year',
            name='minimum_score',
            field=models.CharField(max_length=50, null=True, verbose_name='最低分'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que_image',
            field=models.ImageField(null=True, storage=system.storage.ImageStorage(), upload_to='./quetion/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que_text',
            field=models.CharField(max_length=255, verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='que_view',
            field=models.CharField(max_length=20, null=True, verbose_name='查看次数'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_badge',
            field=models.ImageField(null=True, storage=system.storage.ImageStorage(), upload_to='./badge/', verbose_name='校徽'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_motto',
            field=models.CharField(max_length=60, null=True, verbose_name='校训'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_head',
            field=models.ImageField(null=True, storage=system.storage.ImageStorage(), upload_to='./head/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='用户编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=100, null=True, verbose_name='用户名称'),
        ),
    ]
