# Generated by Django 2.0 on 2018-04-23 14:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180422_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='direction',
            field=models.TextField(blank=True, null=True, verbose_name='就业方向'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='main_class',
            field=models.TextField(blank=True, null=True, verbose_name='主干学科'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='培养目标'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='practice',
            field=models.TextField(blank=True, null=True, verbose_name='实践教学'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='profess_class',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='科类'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='related',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='相关专业'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='tra_require',
            field=models.TextField(blank=True, null=True, verbose_name='培养要求'),
        ),
    ]
