# Generated by Django 2.0 on 2018-04-23 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180423_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=ckeditor.fields.RichTextField(verbose_name='文章标题'),
        ),
    ]
