# Generated by Django 2.0 on 2018-04-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180424_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='majorScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=200, null=True, verbose_name='专业分数')),
                ('school_name', models.CharField(max_length=200, null=True, verbose_name='高校名称')),
                ('aver_score', models.CharField(max_length=50, null=True, verbose_name='平均分')),
                ('highest', models.CharField(max_length=50, null=True, verbose_name='最高分')),
                ('student_loca', models.CharField(max_length=100, null=True, verbose_name='考生地区')),
                ('category', models.CharField(max_length=50, null=True, verbose_name='科别')),
                ('par_year', models.CharField(max_length=10, null=True, verbose_name='年份')),
                ('batch', models.CharField(max_length=100, null=True, verbose_name='批次')),
            ],
            options={
                'verbose_name': '专业录取线',
                'verbose_name_plural': '专业录取线',
            },
        ),
    ]
