# Generated by Django 2.0 on 2018-04-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180426_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='collegeLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_year', models.CharField(max_length=10, null=True, verbose_name='年份')),
                ('batch', models.CharField(max_length=100, null=True, verbose_name='录取批次')),
                ('art_science', models.CharField(max_length=50, null=True, verbose_name='文理科')),
                ('highest_score', models.CharField(max_length=50, null=True, verbose_name='最高分')),
                ('minimum_score', models.CharField(max_length=50, null=True, verbose_name='最低分')),
                ('average_score', models.CharField(max_length=50, null=True, verbose_name='平均分')),
                ('enrill_num', models.CharField(max_length=50, null=True, verbose_name='录取人数')),
                ('school_name', models.CharField(max_length=200, null=True, verbose_name='学校名称')),
            ],
            options={
                'verbose_name': '院校分数线',
                'verbose_name_plural': '院校分数线',
            },
        ),
        migrations.DeleteModel(
            name='collegeLine',
        ),
    ]
