# Generated by Django 2.0 on 2018-04-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180428_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_year', models.CharField(max_length=10, null=True, verbose_name='年份')),
                ('batch', models.CharField(max_length=100, null=True, verbose_name='录取批次')),
                ('art_science', models.CharField(max_length=50, null=True, verbose_name='文理科')),
                ('highest_score', models.CharField(max_length=50, null=True, verbose_name='最高分')),
                ('minimum_score', models.CharField(max_length=50, null=True, verbose_name='最低分')),
                ('average_score', models.CharField(max_length=50, null=True, verbose_name='平均分')),
                ('enrill_num', models.CharField(max_length=50, null=True, verbose_name='录取人数')),
                ('school_name', models.CharField(max_length=200, null=True, verbose_name='学校名称')),
                ('province', models.CharField(max_length=200, null=True, verbose_name='考生地区')),
            ],
            options={
                'verbose_name': '高校分数线',
                'verbose_name_plural': '高校分数线',
            },
        ),
        migrations.CreateModel(
            name='specialtyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=200, null=True, verbose_name='专业名称')),
                ('school_name', models.CharField(max_length=200, null=True, verbose_name='高校名称')),
                ('aver_score', models.CharField(max_length=50, null=True, verbose_name='平均分')),
                ('highest', models.CharField(max_length=50, null=True, verbose_name='最高分')),
                ('minimum', models.CharField(max_length=50, null=True, verbose_name='最低分')),
                ('student_loca', models.CharField(max_length=100, null=True, verbose_name='考生地区')),
                ('category', models.CharField(max_length=50, null=True, verbose_name='科别')),
                ('par_year', models.CharField(max_length=10, null=True, verbose_name='年份')),
                ('batch', models.CharField(max_length=100, null=True, verbose_name='批次')),
            ],
            options={
                'verbose_name': '专业分数线',
                'verbose_name_plural': '专业分数线',
            },
        ),
    ]
